export const defaultNodeId = 'success'

const createExtraFormula = (math, segments = [], label = '') => ({ math, segments, label })

const createLeafNode = ({
  id,
  symbol,
  title,
  description,
  intuition,
  references = [],
  related = [],
  examples = [],
  displayFormula = null,
  visualTheme = 'cyan',
  range = '0 to 1',
}) => ({
  id,
  symbol,
  title,
  category: 'subfactor',
  displayFormula,
  formulaSegments: displayFormula ? [{ type: 'node', id, label: symbol }] : undefined,
  extraFormulas: [],
  description,
  intuition,
  range,
  children: [],
  related,
  references,
  examples,
  visualTheme,
})

export const simulatorPresets = [
  {
    id: 'job-hunt',
    title: 'Job Hunt',
    description: 'Moderate base odds, strong dependence on targeting, timing, consistency, sponsorship, and useful feedback loops.',
    defaults: {
      n: 60,
      p0: 0.02,
      S0: 0.56,
      timingBase: 0.62,
      timingTrend: 0.08,
      timingSwing: 0.14,
      goalClarity: 0.72,
      targetFit: 0.74,
      planQuality: 0.68,
      learningBalance: 0.66,
      adherenceRate: 0.85,
      spacingQuality: 0.79,
      recovery: 0.78,
      regulation: 0.75,
      stressTolerance: 0.73,
      control: 0.58,
      support: 0.61,
      tools: 0.64,
      timeResource: 0.52,
      runway: 0.54,
      relevance: 0.53,
      trust: 0.49,
      reach: 0.47,
      activation: 0.5,
      sponsorship: 0.36,
      deepWork: 0.68,
      switchCost: 0.28,
      feedbackQuality: 0.74,
      receptivity: 0.77,
      taskFocus: 0.79,
      cognitiveFlex: 0.72,
      learningOrientation: 0.76,
      updateSpeed: 0.68,
      noveltyTolerance: 0.61,
    },
    highlightedFactors: ['strategy', 'timing', 'network'],
  },
  {
    id: 'startup-pitch',
    title: 'Startup Pitch',
    description: 'Low base odds, heavy leverage from strategy quality, sponsorship, runway, and adaptation under rejection.',
    defaults: {
      n: 36,
      p0: 0.03,
      S0: 0.63,
      timingBase: 0.59,
      timingTrend: 0.11,
      timingSwing: 0.17,
      goalClarity: 0.79,
      targetFit: 0.71,
      planQuality: 0.74,
      learningBalance: 0.63,
      adherenceRate: 0.76,
      spacingQuality: 0.71,
      recovery: 0.82,
      regulation: 0.8,
      stressTolerance: 0.78,
      control: 0.66,
      support: 0.63,
      tools: 0.67,
      timeResource: 0.58,
      runway: 0.65,
      relevance: 0.58,
      trust: 0.55,
      reach: 0.61,
      activation: 0.62,
      sponsorship: 0.44,
      deepWork: 0.72,
      switchCost: 0.24,
      feedbackQuality: 0.69,
      receptivity: 0.72,
      taskFocus: 0.74,
      cognitiveFlex: 0.76,
      learningOrientation: 0.74,
      updateSpeed: 0.77,
      noveltyTolerance: 0.72,
    },
    highlightedFactors: ['strategy', 'environment', 'network'],
  },
  {
    id: 'content-growth',
    title: 'Content Growth',
    description: 'Many attempts, tiny early odds, and lots of upside from cadence, feedback quality, focus, and adaptability.',
    defaults: {
      n: 120,
      p0: 0.012,
      S0: 0.5,
      timingBase: 0.54,
      timingTrend: 0.05,
      timingSwing: 0.21,
      goalClarity: 0.62,
      targetFit: 0.59,
      planQuality: 0.57,
      learningBalance: 0.72,
      adherenceRate: 0.89,
      spacingQuality: 0.83,
      recovery: 0.75,
      regulation: 0.73,
      stressTolerance: 0.69,
      control: 0.56,
      support: 0.51,
      tools: 0.63,
      timeResource: 0.49,
      runway: 0.47,
      relevance: 0.43,
      trust: 0.39,
      reach: 0.44,
      activation: 0.46,
      sponsorship: 0.24,
      deepWork: 0.74,
      switchCost: 0.31,
      feedbackQuality: 0.86,
      receptivity: 0.84,
      taskFocus: 0.83,
      cognitiveFlex: 0.79,
      learningOrientation: 0.86,
      updateSpeed: 0.81,
      noveltyTolerance: 0.76,
    },
    highlightedFactors: ['consistency', 'feedback', 'adaptability'],
  },
]

export const atlasGroups = [
  {
    title: 'Foundation',
    description: 'These define the raw shot count, baseline odds, and opportunity window before the rest of the system modifies anything.',
    ids: ['attempts', 'baseChance', 'timing'],
  },
  {
    title: 'Direct Boosters',
    description: 'These shape the quality of each live attempt.',
    ids: ['skill', 'strategy', 'environment', 'network', 'focus'],
  },
  {
    title: 'Growth Engine',
    description: 'These determine whether repeated effort actually teaches the system something.',
    ids: ['feedback', 'adaptability'],
  },
  {
    title: 'Staying Power',
    description: 'These decide whether planned attempts keep happening under real-world friction and setbacks.',
    ids: ['consistency', 'resilience'],
  },
]

export const researchSources = [
  {
    id: 'practice',
    title: 'Deliberate practice explains some performance variance, not all of it',
    host: 'PubMed',
    href: 'https://pubmed.ncbi.nlm.nih.gov/24986855/',
    insight: 'Practice matters, but it does not explain everything, and domain differences are large.',
  },
  {
    id: 'grit',
    title: 'Perseverance predicts outcomes more than consistency of interest',
    host: 'PubMed',
    href: 'https://pubmed.ncbi.nlm.nih.gov/27845531/',
    insight: 'Consistency is closer to reliable follow-through than to motivational mythology.',
  },
  {
    id: 'feedback',
    title: 'Feedback often helps, but some interventions reduce performance',
    host: 'ResearchGate',
    href: 'https://www.researchgate.net/profile/Avraham-Kluger/publication/232458848_The_Effects_of_Feedback_Interventions_on_Performance_A_Historical_Review_a_Meta-Analysis_and_a_Preliminary_Feedback_Intervention_Theory/links/562c652908aef25a2441d0c3/The-Effects-of-Feedback-Interventions-on-Performance-A-Historical-Review-a-Meta-Analysis-and-a-Preliminary-Feedback-Intervention-Theory.pdf',
    insight: 'The value of feedback depends on where it places attention: task, learning, or ego threat.',
  },
  {
    id: 'planning',
    title: 'Planning and learning work best together',
    host: 'PubMed',
    href: 'https://pubmed.ncbi.nlm.nih.gov/21744940/',
    insight: 'Strategy quality improves when plans can learn instead of locking too early.',
  },
  {
    id: 'timing',
    title: 'Timing and market conditions can shape outcomes for years',
    host: 'NBER',
    href: 'https://www.nber.org/system/files/working_papers/w26638/w26638.pdf',
    insight: 'Opportunity windows are real, which is why timing gets its own variable.',
  },
  {
    id: 'resources',
    title: 'Resources and control predict engagement better than demands alone',
    host: 'ScienceDirect',
    href: 'https://www.sciencedirect.com/science/article/abs/pii/S0001879106000935',
    insight: 'Environment changes bandwidth, not just mood.',
  },
  {
    id: 'networking',
    title: 'Networks matter through access, information, trust, and sponsorship',
    host: 'ResearchGate',
    href: 'https://www.researchgate.net/publication/228831713_A_Social_Capital_Theory_of_Career_Success',
    insight: 'Useful networks are about quality-adjusted access, not raw contact count.',
  },
  {
    id: 'resilience-study',
    title: 'Resilience protects future attempts from collapsing after setbacks',
    host: 'ScienceDirect',
    href: 'https://www.sciencedirect.com/science/article/abs/pii/S0272735824000497',
    insight: 'Resilience behaves like a recovery resource more than a simple win multiplier.',
  },
  {
    id: 'focus-study',
    title: 'Task switching leaves attention residue',
    host: 'ScienceDirect',
    href: 'https://www.sciencedirect.com/science/article/abs/pii/S0749597809000399',
    insight: 'Focus deserves its own factor because interruptions damage the next attempt.',
  },
  {
    id: 'adaptability-study',
    title: 'Adaptive performance is a distinct and useful capability',
    host: 'University of Salzburg',
    href: 'https://uni-salzburg.elsevierpure.com/en/publications/how-important-is-cognitive-ability-when-adapting-to-changes-a-met',
    insight: 'Adaptability matters because conditions and methods change under your feet.',
  },
  {
    id: 'learning-curves',
    title: 'Learning curves differ sharply across people and tasks',
    host: 'ScienceDirect',
    href: 'https://www.sciencedirect.com/science/article/pii/S002224962300072X',
    insight: 'One universal skill-growth curve is too simple for real human learning.',
  },
  {
    id: 'spacing-study',
    title: 'Spacing changes retention and learning quality',
    host: 'ScienceDirect',
    href: 'https://www.sciencedirect.com/science/article/abs/pii/S2211949315000022',
    insight: 'Steady cadence is not just aesthetic; it changes how well learning sticks.',
  },
  {
    id: 'planning-balance',
    title: 'Planning can backfire when learning overloads the system',
    host: 'ScienceDirect',
    href: 'https://www.sciencedirect.com/science/article/abs/pii/S0883902608001109',
    insight: 'Learning balance matters because both rigidity and overload can hurt execution.',
  },
]

export const formulaNodes = [
  {
    id: 'success',
    symbol: 'P(success by n)',
    title: 'Probability of at least one success by n',
    category: 'core',
    displayFormula: 'P(\\text{success by } n)=1-\\prod_{t=1}^{n}\\left(1-a_t\\,p_t\\right)',
    formulaSegments: [
      { type: 'text', value: 'P(success by ' },
      { type: 'node', id: 'attempts', label: 'n' },
      { type: 'text', value: ') = 1 - product_t(1 - ' },
      { type: 'node', id: 'attemptActivation', label: 'a_t' },
      { type: 'text', value: ' * ' },
      { type: 'node', id: 'attemptQuality', label: 'p_t' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [
      createExtraFormula('1-(1-p)^n', [
        { type: 'text', value: '1 - (1 - ' },
        { type: 'node', id: 'baseChance', label: 'p' },
        { type: 'text', value: ')^' },
        { type: 'node', id: 'attempts', label: 'n' },
      ], 'Classic identical-trials form'),
      createExtraFormula('\\lim_{n\\to\\infty}\\left(1-(1-p)^n\\right)=1\\quad\\text{for }p>0', [
        { type: 'text', value: 'lim_{n->infinity}(1 - (1 - ' },
        { type: 'node', id: 'baseChance', label: 'p' },
        { type: 'text', value: ')^n) = 1 for p > 0' },
      ], 'Limit form'),
    ],
    description: 'This is the master probability for getting at least one success across many attempts, while letting both attempt quality and attempt activation change over time.',
    intuition: 'Volume matters when every try has a real chance and the system keeps producing actual attempts.',
    range: '0 to 1',
    children: ['attempts', 'attemptActivation', 'attemptQuality'],
    related: ['baseChance', 'timing'],
    references: ['practice', 'timing'],
    examples: ['If p = 0.1 and n = 10, then 1 - 0.9^10 approx 0.651.', 'If p = 0.1 and n = 100, then 1 - 0.9^100 approx 0.99997.'],
    visualTheme: 'cyan',
  },
  {
    id: 'attempts',
    symbol: 'n',
    title: 'Planned attempts',
    category: 'foundation',
    displayFormula: 'n=\\text{planned attempts}',
    formulaSegments: [
      { type: 'node', id: 'attempts', label: 'n' },
      { type: 'text', value: ' = planned attempts' },
    ],
    extraFormulas: [],
    description: 'The number of shots you plan to take. In the richer model, not every planned shot turns into a real attempt.',
    intuition: 'Raw volume matters, but only if enough attempts survive real life.',
    range: 'positive whole numbers',
    children: [],
    related: ['consistency', 'resilience'],
    references: ['grit'],
    examples: ['60 targeted job applications.', '120 published content pieces.'],
    visualTheme: 'amber',
  },
  {
    id: 'baseChance',
    symbol: 'p_0',
    title: 'Base probability per attempt',
    category: 'foundation',
    displayFormula: '0\\leq p_0\\leq 1',
    formulaSegments: [
      { type: 'node', id: 'baseChance', label: 'p_0' },
      { type: 'text', value: ' is the baseline chance before modifiers' },
    ],
    extraFormulas: [],
    description: 'The neutral per-attempt chance before skill, strategy, timing, network, and the rest of the stack modify it.',
    intuition: 'Some games start generous. Others start brutal.',
    range: '0 to 1',
    children: [],
    related: ['attemptQuality'],
    references: ['practice'],
    examples: ['A 2% cold outreach conversion rate means p_0 = 0.02.', 'If p_0 = 0, persistence alone cannot create a win.'],
    visualTheme: 'amber',
  },
  {
    id: 'attemptActivation',
    symbol: 'a_t',
    title: 'Attempt activation',
    category: 'core',
    displayFormula: 'a_t=C_t\\cdot R_t',
    formulaSegments: [
      { type: 'node', id: 'attemptActivation', label: 'a_t' },
      { type: 'text', value: ' = ' },
      { type: 'node', id: 'consistency', label: 'C_t' },
      { type: 'text', value: ' * ' },
      { type: 'node', id: 'resilience', label: 'R_t' },
    ],
    extraFormulas: [],
    description: 'This is the probability that the planned attempt actually happens at usable quality.',
    intuition: 'A perfect plan still fails if you do not show up or if setbacks knock future attempts offline.',
    range: '0 to 1',
    children: ['consistency', 'resilience'],
    related: ['attempts'],
    references: ['grit', 'resilience-study'],
    examples: ['High consistency but low resilience still collapses after a bad streak.'],
    visualTheme: 'amber',
  },
  {
    id: 'attemptQuality',
    symbol: 'p_t',
    title: 'Success chance of the live attempt',
    category: 'core',
    displayFormula:
      'p_t=\\sigma\\!\\Big(\\operatorname{logit}(p_0)+\\beta_S S_t+\\beta_G G_t+\\beta_T T_t+\\beta_E E_t+\\beta_N N_t+\\beta_U U_t+\\beta_{SN}S_tN_t+\\beta_{GT}G_tT_t\\Big)',
    formulaSegments: [
      { type: 'node', id: 'attemptQuality', label: 'p_t' },
      { type: 'text', value: ' = sigma(logit(' },
      { type: 'node', id: 'baseChance', label: 'p_0' },
      { type: 'text', value: ') + beta_S*' },
      { type: 'node', id: 'skill', label: 'S_t' },
      { type: 'text', value: ' + beta_G*' },
      { type: 'node', id: 'strategy', label: 'G_t' },
      { type: 'text', value: ' + beta_T*' },
      { type: 'node', id: 'timing', label: 'T_t' },
      { type: 'text', value: ' + beta_E*' },
      { type: 'node', id: 'environment', label: 'E_t' },
      { type: 'text', value: ' + beta_N*' },
      { type: 'node', id: 'network', label: 'N_t' },
      { type: 'text', value: ' + beta_U*' },
      { type: 'node', id: 'focus', label: 'U_t' },
      { type: 'text', value: ' + beta_SN*' },
      { type: 'node', id: 'skill', label: 'S_t' },
      { type: 'text', value: '*' },
      { type: 'node', id: 'network', label: 'N_t' },
      { type: 'text', value: ' + beta_GT*' },
      { type: 'node', id: 'strategy', label: 'G_t' },
      { type: 'text', value: '*' },
      { type: 'node', id: 'timing', label: 'T_t' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [
      createExtraFormula('\\sigma(x)=\\frac{1}{1+e^{-x}}', [{ type: 'text', value: 'sigma(x) = 1 / (1 + e^-x)' }], 'Logistic squashing function'),
      createExtraFormula('\\operatorname{logit}(p_0)=\\ln\\!\\left(\\frac{p_0}{1-p_0}\\right)', [
        { type: 'text', value: 'logit(' },
        { type: 'node', id: 'baseChance', label: 'p_0' },
        { type: 'text', value: ') = ln(p_0 / (1 - p_0))' },
      ], 'Baseline log-odds transform'),
    ],
    description: 'This is the research-informed live attempt probability: bounded, saturating, and explicitly shaped by interaction effects.',
    intuition: 'A warm network matters more when you can convert it, and a sharp strategy matters more when the window is actually open.',
    range: '0 to 1',
    children: ['baseChance', 'skill', 'strategy', 'timing', 'environment', 'network', 'focus'],
    related: ['feedback', 'adaptability'],
    references: ['networking', 'timing'],
    examples: ['Good strategy in terrible timing can still underperform.', 'Skill x network and strategy x timing are explicit interaction terms here.'],
    visualTheme: 'cyan',
  },
  {
    id: 'consistency',
    symbol: 'C_t',
    title: 'Consistency ratio',
    category: 'persistence',
    displayFormula: 'C_t=A_t^{(cons)}\\cdot Q_t^{(spacing)}',
    formulaSegments: [
      { type: 'node', id: 'consistency', label: 'C_t' },
      { type: 'text', value: ' = ' },
      { type: 'node', id: 'adherenceRate', label: 'A_t^(cons)' },
      { type: 'text', value: ' * ' },
      { type: 'node', id: 'spacingQuality', label: 'Q_t^(spacing)' },
    ],
    extraFormulas: [],
    description: 'Consistency combines actual adherence with cadence quality instead of pretending all repeated effort is equally well spaced.',
    intuition: 'Doing some of the work late and in bursts is not the same as a stable operating rhythm.',
    range: '0 to 1',
    children: ['adherenceRate', 'spacingQuality'],
    related: ['attemptActivation', 'focus'],
    references: ['grit', 'spacing-study'],
    examples: ['You planned 30 attempts, delivered 24, and kept the cadence stable.'],
    visualTheme: 'amber',
  },
  {
    id: 'resilience',
    symbol: 'R_t',
    title: 'Emotional resilience',
    category: 'persistence',
    displayFormula: 'R_t=(\\text{recovery}\\cdot\\text{regulation}\\cdot\\text{stressTolerance})^{1/3}',
    formulaSegments: [
      { type: 'node', id: 'resilience', label: 'R_t' },
      { type: 'text', value: ' = geometricMean(' },
      { type: 'node', id: 'recovery', label: 'recovery' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'regulation', label: 'regulation' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'stressTolerance', label: 'stressTolerance' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [],
    description: 'Resilience is modeled as recovery, emotional regulation, and stress tolerance together rather than a vague grit aura.',
    intuition: 'Sometimes the winner is just the person whose system did not collapse after the seventh no.',
    range: '0 to 1',
    children: ['recovery', 'regulation', 'stressTolerance'],
    related: ['attemptActivation', 'feedback'],
    references: ['resilience-study'],
    examples: ['You keep performing even when uncertainty and rejection stack up.'],
    visualTheme: 'mint',
  },
  {
    id: 'skill',
    symbol: 'S_t',
    title: 'Skill level',
    category: 'direct',
    displayFormula: 'S_t',
    formulaSegments: [{ type: 'node', id: 'skill', label: 'S_t' }],
    extraFormulas: [
      createExtraFormula('S_{t+1}=S_t+\\eta_S C_t U_t F_t A_t E_t(1-S_t)-\\lambda_S(1-U_t)S_t', [
        { type: 'node', id: 'skill', label: 'S_t' },
        { type: 'text', value: ' -> S_(t+1) depends on ' },
        { type: 'node', id: 'consistency', label: 'C_t' },
        { type: 'text', value: ', ' },
        { type: 'node', id: 'focus', label: 'U_t' },
        { type: 'text', value: ', ' },
        { type: 'node', id: 'feedback', label: 'F_t' },
        { type: 'text', value: ', ' },
        { type: 'node', id: 'adaptability', label: 'A_t' },
        { type: 'text', value: ', and ' },
        { type: 'node', id: 'environment', label: 'E_t' },
      ], 'Skill update'),
      createExtraFormula('S_0=\\text{starting skill}', [{ type: 'text', value: 'S_0 = starting skill before the loop begins' }], 'Initial condition'),
    ],
    description: 'Skill is an evolving state, not a fixed trait. The more usable reps, focus, feedback, adaptation, and support you have, the faster it rises.',
    intuition: 'Repeated effort only becomes mastery when the loop is actually teachable.',
    range: '0 to 1',
    children: [],
    related: ['feedback', 'adaptability', 'focus', 'environment', 'consistency'],
    references: ['practice', 'learning-curves'],
    examples: ['A sharper portfolio, better pitch, better editing judgment, better sales call.'],
    visualTheme: 'cyan',
  },
  {
    id: 'strategy',
    symbol: 'G_t',
    title: 'Strategy quality',
    category: 'direct',
    displayFormula: 'G_t=(g_{goal}\\cdot g_{targetFit}\\cdot g_{plan}\\cdot g_{learn-balance})^{1/4}',
    formulaSegments: [
      { type: 'node', id: 'strategy', label: 'G_t' },
      { type: 'text', value: ' = geometricMean(' },
      { type: 'node', id: 'goalClarity', label: 'g_goal' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'targetFit', label: 'g_targetFit' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'planQuality', label: 'g_plan' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'learningBalance', label: 'g_learn-balance' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [
      createExtraFormula('G_{t+1}=G_t+\\eta_G F_t A_t(1-G_t)', [
        { type: 'node', id: 'strategy', label: 'G_t' },
        { type: 'text', value: ' -> G_(t+1) improves through ' },
        { type: 'node', id: 'feedback', label: 'F_t' },
        { type: 'text', value: ' and ' },
        { type: 'node', id: 'adaptability', label: 'A_t' },
      ], 'Strategy update'),
      createExtraFormula('g_{learn-balance}=1-\\gamma(L_t-L^*)^2', [
        { type: 'node', id: 'learningBalance', label: 'g_learn-balance' },
        { type: 'text', value: ' = 1 - gamma * (L_t - L*)^2' },
      ], 'Planning-learning balance'),
    ],
    description: 'Strategy is the quality of the plan itself: clear target, good target fit, strong planning, and the right planning-versus-learning balance.',
    intuition: 'Wrong ladder, impressive climbing.',
    range: '0 to 1',
    children: ['goalClarity', 'targetFit', 'planQuality', 'learningBalance'],
    related: ['timing', 'feedback', 'adaptability'],
    references: ['planning', 'planning-balance'],
    examples: ['Targeted applications beat random applications.', 'Customer-aware positioning beats generic feature dumping.'],
    visualTheme: 'violet',
  },
  {
    id: 'timing',
    symbol: 'T_t',
    title: 'Timing quality',
    category: 'foundation',
    displayFormula: 'T_t=\\text{normalized opportunity index at time }t',
    formulaSegments: [
      { type: 'node', id: 'timing', label: 'T_t' },
      { type: 'text', value: ' = normalized opportunity index at attempt t' },
    ],
    extraFormulas: [
      createExtraFormula('T_t=\\operatorname{clamp}\\!\\left(T_0+m\\tau_t+s\\sin(2\\pi\\tau_t),0,1\\right)', [
        { type: 'node', id: 'timing', label: 'T_t' },
        { type: 'text', value: ' = clamp(' },
        { type: 'node', id: 'timingBase', label: 'T_0' },
        { type: 'text', value: ' + ' },
        { type: 'node', id: 'timingTrend', label: 'm' },
        { type: 'text', value: ' * tau_t + ' },
        { type: 'node', id: 'timingSwing', label: 's' },
        { type: 'text', value: ' * sin(2p tau_t))' },
      ], 'Simulator operationalization'),
    ],
    description: 'Timing measures whether the market window, hiring climate, audience demand, or other opportunity conditions are favorable right now.',
    intuition: 'Average effort can look brilliant in the right window and brilliant effort can look invisible in the wrong one.',
    range: '0 to 1',
    children: ['timingBase', 'timingTrend', 'timingSwing'],
    related: ['strategy', 'attemptQuality'],
    references: ['timing'],
    examples: ['A hiring surge, a rising demand pocket, a favorable budget cycle.'],
    visualTheme: 'amber',
  },
  {
    id: 'environment',
    symbol: 'E_t',
    title: 'Environment and resources',
    category: 'direct',
    displayFormula: 'E_t=(e_{control}\\cdot e_{support}\\cdot e_{tools}\\cdot e_{time}\\cdot e_{runway})^{1/5}',
    formulaSegments: [
      { type: 'node', id: 'environment', label: 'E_t' },
      { type: 'text', value: ' = geometricMean(' },
      { type: 'node', id: 'control', label: 'control' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'support', label: 'support' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'tools', label: 'tools' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'timeResource', label: 'time' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'runway', label: 'runway' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [],
    description: 'Environment bundles autonomy, support, tools, time, and runway. The model uses a geometric mean so one missing pillar can choke the whole system.',
    intuition: 'Great talent in a chaotic environment still leaks performance everywhere.',
    range: '0 to 1',
    children: ['control', 'support', 'tools', 'timeResource', 'runway'],
    related: ['focus', 'skill'],
    references: ['resources'],
    examples: ['Protected time, decent tools, and enough runway to iterate.'],
    visualTheme: 'mint',
  },
  {
    id: 'network',
    symbol: 'N_t',
    title: 'Network effectiveness',
    category: 'direct',
    displayFormula: 'N_t=(n_{relevance}\\cdot n_{trust}\\cdot n_{reach}\\cdot n_{activation}\\cdot n_{sponsorship})^{1/5}',
    formulaSegments: [
      { type: 'node', id: 'network', label: 'N_t' },
      { type: 'text', value: ' = geometricMean(' },
      { type: 'node', id: 'relevance', label: 'relevance' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'trust', label: 'trust' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'reach', label: 'reach' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'activation', label: 'activation' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'sponsorship', label: 'sponsorship' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [],
    description: 'Network is quality-adjusted access to useful opportunities. This exact version restores sponsorship as a first-class term.',
    intuition: 'A huge network with no trust or activation still does not open real doors.',
    range: '0 to 1',
    children: ['relevance', 'trust', 'reach', 'activation', 'sponsorship'],
    related: ['strategy', 'timing'],
    references: ['networking'],
    examples: ['A warm intro reaches the real decision-maker.', 'Trusted sponsors compress time and credibility.'],
    visualTheme: 'coral',
  },
  {
    id: 'focus',
    symbol: 'U_t',
    title: 'Focus ratio',
    category: 'direct',
    displayFormula: 'U_t=u_{deepWork}\\cdot(1-u_{switchCost})',
    formulaSegments: [
      { type: 'node', id: 'focus', label: 'U_t' },
      { type: 'text', value: ' = ' },
      { type: 'node', id: 'deepWork', label: 'deepWork' },
      { type: 'text', value: ' * (1 - ' },
      { type: 'node', id: 'switchCost', label: 'switchCost' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [],
    description: 'Focus measures how much meaningful effort happens in uninterrupted concentration rather than constant switching and residue.',
    intuition: 'Concentrated effort compounds. Fragmented effort leaks force.',
    range: '0 to 1',
    children: ['deepWork', 'switchCost'],
    related: ['skill', 'consistency'],
    references: ['focus-study'],
    examples: ['One protected block on the main goal beats twelve fractured bursts.'],
    visualTheme: 'cyan',
  },
  {
    id: 'feedback',
    symbol: 'F_t',
    title: 'Feedback and learning rate',
    category: 'growth',
    displayFormula: 'F_t=Q_t^{(fb)}\\cdot R_t^{(fb)}\\cdot H_t^{(task)}',
    formulaSegments: [
      { type: 'node', id: 'feedback', label: 'F_t' },
      { type: 'text', value: ' = ' },
      { type: 'node', id: 'feedbackQuality', label: 'Q_t^(fb)' },
      { type: 'text', value: ' * ' },
      { type: 'node', id: 'receptivity', label: 'R_t^(fb)' },
      { type: 'text', value: ' * ' },
      { type: 'node', id: 'taskFocus', label: 'H_t^(task)' },
    ],
    extraFormulas: [],
    description: 'Feedback controls how much usable signal comes back from each attempt and whether the next attempt gets sharper.',
    intuition: 'Without learning, repeated effort becomes deluxe repetition.',
    range: '0 to 1',
    children: ['feedbackQuality', 'receptivity', 'taskFocus'],
    related: ['skill', 'strategy', 'adaptability'],
    references: ['feedback'],
    examples: ['Specific notes plus genuine follow-through.', 'Feedback aimed at ego can lower performance.'],
    visualTheme: 'violet',
  },
  {
    id: 'adaptability',
    symbol: 'A_t',
    title: 'Adaptability',
    category: 'growth',
    displayFormula: 'A_t=(a_{cognitive}\\cdot a_{learning}\\cdot a_{update}\\cdot a_{novelty})^{1/4}',
    formulaSegments: [
      { type: 'node', id: 'adaptability', label: 'A_t' },
      { type: 'text', value: ' = geometricMean(' },
      { type: 'node', id: 'cognitiveFlex', label: 'cognitiveFlex' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'learningOrientation', label: 'learningOrientation' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'updateSpeed', label: 'updateSpeed' },
      { type: 'text', value: ', ' },
      { type: 'node', id: 'noveltyTolerance', label: 'noveltyTolerance' },
      { type: 'text', value: ')' },
    ],
    extraFormulas: [],
    description: 'Adaptability is how quickly and intelligently you update after reality shows you something new.',
    intuition: 'Rigid systems keep replaying obsolete moves.',
    range: '0 to 1',
    children: ['cognitiveFlex', 'learningOrientation', 'updateSpeed', 'noveltyTolerance'],
    related: ['feedback', 'strategy', 'skill'],
    references: ['adaptability-study'],
    examples: ['You revise the pitch after real buyer reactions instead of worshipping stale tactics.'],
    visualTheme: 'mint',
  },
  createLeafNode({
    id: 'adherenceRate',
    symbol: 'A_t^(cons)',
    title: 'Adherence at attempt t',
    description: 'How much of the intended plan actually happened.',
    intuition: 'Plans only matter if they turn into reps.',
    references: ['grit'],
    related: ['consistency'],
    examples: ['Made 24 of 30 planned attempts.'],
    visualTheme: 'amber',
  }),
  createLeafNode({
    id: 'spacingQuality',
    symbol: 'Q_t^(spacing)',
    title: 'Spacing quality',
    description: 'How smooth the cadence is instead of effort arriving in bursts and droughts.',
    intuition: 'Cadence matters because learning and recovery both hate chaos.',
    references: ['spacing-study'],
    related: ['consistency', 'focus'],
    examples: ['A stable weekly rhythm instead of a panic sprint.'],
    displayFormula: 'e^{-CV(\\Delta t)}',
    visualTheme: 'amber',
  }),
  createLeafNode({
    id: 'recovery',
    symbol: 'recovery',
    title: 'Recovery speed',
    description: 'How fast you return to useful action after a miss or rejection.',
    intuition: 'Fast recovery keeps the next attempt alive.',
    references: ['resilience-study'],
    related: ['resilience'],
    examples: ['Back on the horse tomorrow, not three weeks later.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'regulation',
    symbol: 'regulation',
    title: 'Emotion regulation',
    description: 'The ability to stay task-oriented instead of getting hijacked by emotion.',
    intuition: 'Resilience is not calmness. It is functionality under heat.',
    references: ['resilience-study'],
    related: ['resilience', 'feedback'],
    examples: ['Taking criticism without spiraling.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'stressTolerance',
    symbol: 'stressTolerance',
    title: 'Stress tolerance',
    description: 'How well you continue functioning while uncertainty, pressure, and repeated misses accumulate.',
    intuition: 'Some systems bend under pressure. Others break.',
    references: ['resilience-study'],
    related: ['resilience'],
    examples: ['You can stay coherent during a rough stretch.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'goalClarity',
    symbol: 'g_goal',
    title: 'Goal clarity',
    description: 'Whether the target is specific enough that you know what success is and can act toward it.',
    intuition: 'Vague effort usually creates vague outcomes.',
    references: ['planning'],
    related: ['strategy'],
    examples: ['A crisp target role, niche, or audience segment.'],
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'targetFit',
    symbol: 'g_targetFit',
    title: 'Target fit',
    description: 'How well the chosen target matches the value you can actually deliver.',
    intuition: 'Good execution in the wrong market is still misaligned.',
    references: ['planning'],
    related: ['strategy', 'timing'],
    examples: ['The offer and audience actually fit each other.'],
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'planQuality',
    symbol: 'g_plan',
    title: 'Plan quality',
    description: 'The structural quality of the plan itself: sequencing, targeting, positioning, and method choice.',
    intuition: 'Effort can be impressive and still strategically sloppy.',
    references: ['planning'],
    related: ['strategy'],
    examples: ['Clear sequencing, realistic hypotheses, and strong execution logic.'],
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'learningBalance',
    symbol: 'g_learn-balance',
    title: 'Planning-learning balance',
    description: 'How close the system is to the sweet spot between rigid planning and overloaded constant learning.',
    intuition: 'Too little learning blinds you. Too much noisy learning overwhelms you.',
    references: ['planning-balance'],
    related: ['strategy', 'feedback'],
    examples: ['Enough adaptation to learn, not so much chaos that execution dissolves.'],
    displayFormula: '1-\\gamma(L_t-L^*)^2',
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'timingBase',
    symbol: 'T_0',
    title: 'Timing baseline',
    description: 'The starting favorability of the opportunity window.',
    intuition: 'Some seasons open better than others.',
    references: ['timing'],
    related: ['timing'],
    examples: ['Hiring is already warm when you begin.'],
    visualTheme: 'amber',
  }),
  createLeafNode({
    id: 'timingTrend',
    symbol: 'm',
    title: 'Timing trend',
    description: 'The directional drift of the opportunity window over the run.',
    intuition: 'Some markets get hotter while you are in them. Others cool off.',
    references: ['timing'],
    related: ['timing'],
    examples: ['A steady tailwind or a steady tightening.'],
    range: '-1 to 1',
    visualTheme: 'amber',
  }),
  createLeafNode({
    id: 'timingSwing',
    symbol: 's',
    title: 'Timing swing amplitude',
    description: 'How volatile the opportunity window is around its baseline trend.',
    intuition: 'Some games have real seasonality and burstiness.',
    references: ['timing'],
    related: ['timing'],
    examples: ['Audience demand or investor appetite arrives in waves.'],
    visualTheme: 'amber',
  }),
  createLeafNode({
    id: 'control',
    symbol: 'e_control',
    title: 'Control',
    description: 'How much autonomy and decision latitude the environment gives you.',
    intuition: 'Control reduces friction and makes adaptation cheaper.',
    references: ['resources'],
    related: ['environment', 'focus'],
    examples: ['You can choose your process, schedule, and iteration speed.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'support',
    symbol: 'e_support',
    title: 'Support',
    description: 'The quality of help, mentorship, and stabilizing social backing around the work.',
    intuition: 'Support does not just feel nice. It protects throughput.',
    references: ['resources'],
    related: ['environment', 'resilience'],
    examples: ['Mentors, collaborators, referrals, and people who keep you upright.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'tools',
    symbol: 'e_tools',
    title: 'Tools',
    description: 'The quality of the tools, systems, and infrastructure available to do the work well.',
    intuition: 'Bad tooling quietly taxes every attempt.',
    references: ['resources'],
    related: ['environment'],
    examples: ['Reliable software, automation, and good gear.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'timeResource',
    symbol: 'e_time',
    title: 'Time resource',
    description: 'How much usable time is available for sustained work rather than fragmented leftovers.',
    intuition: 'You cannot deep-work on crumbs forever.',
    references: ['resources'],
    related: ['environment', 'focus'],
    examples: ['Enough protected hours to iterate properly.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'runway',
    symbol: 'e_runway',
    title: 'Runway',
    description: 'How long the system can keep operating before money, energy, or optionality runs out.',
    intuition: 'Runway buys learning time.',
    references: ['resources'],
    related: ['environment', 'timing'],
    examples: ['Cash, savings, emotional bandwidth, or employer runway.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'relevance',
    symbol: 'n_relevance',
    title: 'Network relevance',
    description: 'How closely your relationships align with the opportunity you want.',
    intuition: 'Wrong-room relationships do not open the right doors.',
    references: ['networking'],
    related: ['network'],
    examples: ['The people you know are actually in the field you need.'],
    visualTheme: 'coral',
  }),
  createLeafNode({
    id: 'trust',
    symbol: 'n_trust',
    title: 'Network trust',
    description: 'How much those people actually know, trust, and would vouch for you.',
    intuition: 'Awareness is not endorsement.',
    references: ['networking'],
    related: ['network'],
    examples: ['Someone will actually put their name behind your intro.'],
    visualTheme: 'coral',
  }),
  createLeafNode({
    id: 'reach',
    symbol: 'n_reach',
    title: 'Network reach',
    description: 'How much direct or indirect access the network has to decision-makers and opportunities.',
    intuition: 'Good people in the wrong layer of the graph still bottleneck access.',
    references: ['networking'],
    related: ['network'],
    examples: ['Your network reaches hiring managers, buyers, editors, or partners.'],
    visualTheme: 'coral',
  }),
  createLeafNode({
    id: 'activation',
    symbol: 'n_activation',
    title: 'Network activation',
    description: 'How much of the useful network is actually being activated rather than passively existing.',
    intuition: 'The dormant network is often the fake network.',
    references: ['networking'],
    related: ['network', 'feedback'],
    examples: ['You actually ask, follow up, and keep the loop moving.'],
    visualTheme: 'coral',
  }),
  createLeafNode({
    id: 'sponsorship',
    symbol: 'n_sponsorship',
    title: 'Network sponsorship',
    description: 'Whether trusted people actively advocate for you, not just hand you information.',
    intuition: 'Sponsorship converts social capital into real movement.',
    references: ['networking'],
    related: ['network'],
    examples: ['Someone pulls you into the room and frames you as credible.'],
    visualTheme: 'coral',
  }),
  createLeafNode({
    id: 'deepWork',
    symbol: 'u_deepWork',
    title: 'Deep-work share',
    description: 'The fraction of effort spent in uninterrupted concentration on the main goal.',
    intuition: 'The mind compounds when it is left alone long enough.',
    references: ['focus-study'],
    related: ['focus', 'timeResource'],
    examples: ['A long protected block on the main project.'],
    visualTheme: 'cyan',
  }),
  createLeafNode({
    id: 'switchCost',
    symbol: 'u_switchCost',
    title: 'Switch cost',
    description: 'The interruption and context-switch burden that bleeds performance from the next task.',
    intuition: 'Attention residue is real drag, not imaginary drama.',
    references: ['focus-study'],
    related: ['focus'],
    examples: ['Constant notifications, shallow meetings, too many goals.'],
    visualTheme: 'cyan',
  }),
  createLeafNode({
    id: 'feedbackQuality',
    symbol: 'Q_t^(fb)',
    title: 'Feedback quality',
    description: 'How specific, accurate, and actionable the incoming feedback is.',
    intuition: 'Vague praise or vague criticism teaches almost nothing.',
    references: ['feedback'],
    related: ['feedback'],
    examples: ['Concrete notes tied to the task instead of the ego.'],
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'receptivity',
    symbol: 'R_t^(fb)',
    title: 'Feedback receptivity',
    description: 'How willing and able the system is to absorb useful criticism and act on it.',
    intuition: 'Great feedback wasted on a closed system is still wasted.',
    references: ['feedback'],
    related: ['feedback', 'resilience'],
    examples: ['You can hear the note without treating it like an attack.'],
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'taskFocus',
    symbol: 'H_t^(task)',
    title: 'Task-focused feedback',
    description: 'How much the feedback keeps attention on the work and learning process rather than identity threat.',
    intuition: 'Task focus teaches. Ego focus destabilizes.',
    references: ['feedback'],
    related: ['feedback'],
    examples: ['The note points to the work, not your worth.'],
    visualTheme: 'violet',
  }),
  createLeafNode({
    id: 'cognitiveFlex',
    symbol: 'a_cognitive',
    title: 'Cognitive flexibility',
    description: 'The ability to reason through changing conditions instead of rigidly repeating the same frame.',
    intuition: 'Adaptation starts with being able to see the pattern shift.',
    references: ['adaptability-study'],
    related: ['adaptability'],
    examples: ['You can reframe the problem when the environment changes.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'learningOrientation',
    symbol: 'a_learning',
    title: 'Learning orientation',
    description: 'The extent to which the system is oriented toward learning and improvement rather than defensiveness.',
    intuition: 'Learning-oriented systems convert uncertainty into data faster.',
    references: ['adaptability-study'],
    related: ['adaptability', 'feedback'],
    examples: ['You care more about signal than about looking perfect.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'updateSpeed',
    symbol: 'a_update',
    title: 'Update speed',
    description: 'How quickly useful changes are made after new evidence arrives.',
    intuition: 'Slow updates trap you in stale strategies.',
    references: ['adaptability-study'],
    related: ['adaptability', 'strategy'],
    examples: ['The next iteration already reflects what you learned.'],
    visualTheme: 'mint',
  }),
  createLeafNode({
    id: 'noveltyTolerance',
    symbol: 'a_novelty',
    title: 'Novelty tolerance',
    description: 'How comfortable the system is operating under change, ambiguity, and unfamiliar methods.',
    intuition: 'If novelty itself feels threatening, adaptation slows down.',
    references: ['adaptability-study'],
    related: ['adaptability'],
    examples: ['You can try the unfamiliar method without freezing.'],
    visualTheme: 'mint',
  }),
]

export const formulaNodeMap = Object.fromEntries(formulaNodes.map((node) => [node.id, node]))

